Failed if any test failed

diff --git a/.github/workflows/unit_tests.yml b/.github/workflows/unit_tests.yml
--- a/.github/workflows/unit_tests.yml
+++ b/.github/workflows/unit_tests.yml
@@ -51,16 +51,25 @@
               echo "No relevant files changed. Skipping tests."
               exit 0
             fi
-  
-            while IFS= read -r -d $'\0' file; do # Use null delimiter for robust file handling
+
+            failed_tests=0
+            while IFS= read -r -d $'\0' file; do
               unittest_file="tests/unit/modules/dnac/test_$(basename "$file")"
               echo "::group::$unittest_file"
               if [ -f "$unittest_file" ]; then
                 echo "Running unittest for: $unittest_file"
-                python -m unittest "$unittest_file" || true
+                if ! python -m unittest "$unittest_file"; then
+                  failed_tests=1 # Set failed_tests to 1 if a test fails
+                fi
               else
                 echo "Skipping: No test file found for $file"
               fi
               echo "::endgroup::"
-            done < <(echo "$filtered_files" | tr '\n' '\0') # Convert newlines to nulls
-            echo "Tests completed successfully."
+            done < <(echo "$filtered_files" | tr '\n' '\0')
+
+            if [ "$failed_tests" -eq 1 ]; then
+              echo "Tests completed with failures."
+              exit 1 # Exit with 1 if any test failed
+            else
+              echo "Tests completed successfully."
+            fi
