Simplified paths

diff --git a/.github/workflows/unit_tests.yml b/.github/workflows/unit_tests.yml
--- a/.github/workflows/unit_tests.yml
+++ b/.github/workflows/unit_tests.yml
@@ -10,41 +10,38 @@ env:
   COLLECTION_NAME: dnac
 
 jobs:
-  Module-unittest:
+  unit_tests:
     runs-on: ubuntu-24.04
+    strategy:
+      matrix:
+        python-version: ['3.10', '3.11', '3.12']  # Add more versions if needed
+
     steps:
       - name: Check out code
         uses: actions/checkout@v4
-        with:
-          fetch-depth: 0
 
-      - name: Setup Ansible Environment
-        run: |
-          python -m venv ansible_env
-          source ansible_env/bin/activate
-          pip install ansible
-          export ANSIBLE_COLLECTIONS_PATH=$(python -c "import site; print(site.getsitepackages()[0])")/ansible_collections
-          echo "ANSIBLE_COLLECTIONS_PATH=$ANSIBLE_COLLECTIONS_PATH" >> $GITHUB_ENV
+      - name: Set up Python ${{ matrix.python-version }}
+        uses: actions/setup-python@v5
+        with:
+          python-version: ${{ matrix.python-version }}
 
       - name: Install dependencies
         run: |
-          source ansible_env/bin/activate
-          if [ -f "test-requirements.txt" ]; then
-            pip install -r test-requirements.txt
-          else
-            echo "test-requirements.txt not found. Skipping dependency installation."
-            exit 1
-          fi
+          python -m venv venv
+          source venv/bin/activate
+          pip install ansible
+          ANSIBLE_COLLECTIONS_PATH=$(python -c "import site; print(site.getsitepackages()[0])")/ansible_collections
+          pip install -r test-requirements.txt || (echo "test-requirements.txt not found. Skipping dependency installation." && exit 1)
           ansible-galaxy collection install -f ansible.netcommon
           ansible-galaxy collection build
-          ansible-galaxy collection install -f cisco-dnac* -p ${{ env.ANSIBLE_COLLECTIONS_PATH }}
+          ansible-galaxy collection install -f cisco-dnac* -p $ANSIBLE_COLLECTIONS_PATH
 
       - name: Run tests
+        shell: bash
         run: |
-          source ansible_env/bin/activate
-
-          base_ref=${{ github.base_ref || github.ref }}
-          git fetch origin "$base_ref"  # Fetch the base branch
+          source venv/bin/activate
+          base_ref="${{ github.base_ref || github.ref }}"
+          git fetch origin "$base_ref"
 
           echo "::group::filtered_files"
           filtered_files=$(git diff --name-only "origin/$base_ref" HEAD | grep '^plugins/modules/.*workflow_manager\.py$' || true)
@@ -58,7 +55,6 @@ jobs:
 
           failed=0
           failed_count=0
-
           while IFS= read -r -d $'\0' file; do
             unittest_file="tests/unit/modules/dnac/test_$(basename "$file")"
             echo "::group::$unittest_file"
